import { ArrowRight, Check, Eye, Lock, Megaphone } from 'lucide-react';
import { Scoreboard } from '../../src/core/teams/Scoreboard';
import { Timer } from '../../src/core/play/TimerView';
import { RevealAnswer } from '../../src/components/RevealAnswer';
import { useShortcuts } from '../../src/core/projector';
import { legacyExtraShortcuts } from './legacy-shortcuts';
import { advance, confirmClues, currentRound, lockGuesses, markRemainingMissed, reveal, reviewRound, roundComplete, scoreTeam, timed } from './logic';
import { ProductPicture } from './ProductPicture';
import { Rules } from './Rules';
import type { Context } from './types';

export function Stage(ctx: Context) {
  const { segment, event, update, updateEvent } = ctx, g = segment.game, r = currentRound(g);
  useShortcuts(legacyExtraShortcuts, ctx, segment.phase === 'play');
  if (!r) return <div className="empty-state"><h2>Prepare your team briefs first.</h2><button className="button primary" onClick={() => update(s => { s.phase = 'setup'; s.setupStepId = 'game'; })}>Game setup</button></div>;
  const team = event.teams.find(t => t.id === r.teamId);
  if (!team) return <div className="empty-state">This commercial’s team is missing.</div>;
  const pending = Object.values(r.results).filter(result => result === null).length;
  const ready = roundComplete(r), last = g.index === g.rounds.length - 1;
  const phases = { rules: 'THE 30-SECOND BRIEF', prepare: 'THE WRITERS’ ROOM', perform: 'ON AIR', guess: 'NAME THAT PRODUCT', reveal: 'THE BIG REVEAL' };
  return <div className="stage-layout pid-stage"><main className="game-stage">
    <header className="pid-round-head"><div><span className="eyebrow">{g.step === 'rules' || g.step === 'prepare' ? 'PRODUCT IN DISGUISE' : `COMMERCIAL ${g.index + 1} / ${g.rounds.length}`}</span><div className="pid-step"><span className="team-dot" style={{ background: g.step === 'prepare' || g.step === 'rules' ? 'var(--yellow)' : team.color }}/>{phases[g.step]}</div></div>{timed(g) ? <Timer state={g.timer} label={g.step === 'prepare' ? 'Preparation timer' : g.step === 'perform' ? 'Commercial timer' : 'Guessing timer'} onChange={timer => update(s => { s.game.timer = timer; })}/> : <span className="pid-stake">+{segment.points.correct}<small>per correct guess</small></span>}</header>
    <section className="pid-scene">
      {g.step === 'rules' ? <div className="pid-intro"><span className="eyebrow">THE AD BREAK</span><h1>Sell the ordinary.<br/><span className="accent">Make it extraordinary.</span></h1><Rules points={segment.points.correct}/><p>{g.rounds.length} teams · {g.rounds.length - 1} guessing turns each · up to {(g.rounds.length - 1) * segment.points.correct} points per team</p></div> : g.step === 'prepare' ? <div className="pid-intro"><span className="eyebrow">EVERY TEAM PREPARES TOGETHER</span><h1>Build your commercial.</h1><div className="pid-story-beats"><article><b>01</b><h2>The problem</h2><p>Make an everyday inconvenience hilariously dramatic.</p></article><article><b>02</b><h2>The solution</h2><p>Introduce your secret product. Communicate both required clues.</p></article><article><b>03</b><h2>The tagline</h2><p>Give it a ridiculous new name and a memorable closing line.</p></article></div><p>Keep the real product and its name hidden. You have {segment.settings.performanceSeconds} seconds on air.</p><p className="muted">Choose roles: write, direct, narrate, act or keep time. One volunteer can narrate from their seat.</p></div> : g.step === 'perform' ? <div className="pid-on-air"><div className="pid-air-sign"><Megaphone size={24}/> ON AIR</div><p className="pid-team-name" style={{ color: team.color }}>{team.name}</p><h1>Your commercial starts now.</h1><p>Everyone else: watch for the clues.<br/>Keep your guesses within your team.</p><label className="pid-confirm"><input type="checkbox" checked={r.cluesConfirmed} onChange={e => update(s => confirmClues(s, e.target.checked))}/> Both required clues included</label><p className="muted pid-host-note">Host: ask for the missing clue before collecting guesses.</p></div> : g.step === 'guess' ? <div className="pid-on-air"><span className="eyebrow">AFTER {team.name.toUpperCase()}’S ADVERTISEMENT</span><h1>What were they selling?</h1><p>Every audience team commits to one product.<br/>Write your answer or send it privately to the host.</p><p className="pid-note">{team.name} presented this round. The other {event.teams.length - 1} teams can score.</p>{r.guessesLocked && <p className="pid-locked"><Lock size={22}/> All guesses are in. Ready for the reveal.</p>}</div> : <div className="pid-product-reveal" key={r.id}><div className="polaroid now-reveal pid-polaroid"><ProductPicture product={r.product}/><span className="handwritten polaroid-caption">Just an everyday legend.</span></div><RevealAnswer eyebrow="ALL THAT… FOR A" title={r.product.name} description={`Or, as an ad agency might call it: “${r.product.tagline}”.`}><div className="pid-reveal-clues">{r.product.clues.map(clue => <p key={clue}><Check size={18}/>{clue}</p>)}</div><p className="pid-accepted">Accept: {r.product.acceptedAnswers.join(' · ')}</p></RevealAnswer></div>}
    </section>
    {g.step === 'reveal' && <div className="pid-awards" aria-label="Audience results"><span>Correct guessing teams · click again to mark missed. {team.name} receives 0 this turn.</span><div>{event.teams.map((t, i) => t.id === r.teamId ? null : <button key={t.id} className="button secondary" aria-label={`Award ${t.name}`} aria-pressed={r.results[t.id] === 'correct'} onClick={() => scoreTeam(ctx, i)}><kbd>{i + 1}</kbd><span>{t.name}</span><b>{r.results[t.id] === 'correct' ? `✓ +${segment.points.correct}` : r.results[t.id] === 'missed' ? '0' : `+${segment.points.correct}`}</b></button>)}</div>{pending > 0 && <button className="button subtle small-button" onClick={() => markRemainingMissed(ctx)}>Mark remaining missed</button>}</div>}
    <footer className="pid-actions"><span>{g.step === 'rules' ? 'Briefs are private. Products stay hidden until each reveal.' : g.step === 'prepare' ? 'Timer finished? Host: bring everyone back and start the first ad.' : g.step === 'perform' ? 'Host: confirm both clues, then collect the audience guesses.' : g.step === 'guess' ? 'Collect every audience answer before revealing. Presenters sit out this guess.' : pending ? `Record ${pending} more audience ${pending === 1 ? 'result' : 'results'} to continue.` : 'Enjoy the reveal, then continue.'}</span>
      {g.step === 'guess' ? <div className="button-row">{!r.guessesLocked && <button className="button secondary" onClick={() => update(s => lockGuesses(s))}><Lock size={18}/> All guesses collected</button>}<button className="button primary large" disabled={!r.guessesLocked} onClick={() => update(reveal)}><Eye size={19}/> Reveal the product</button></div> : <button className="button primary large" disabled={g.step === 'perform' && !r.cluesConfirmed || g.step === 'reveal' && !ready} onClick={() => update(s => advance(s))}>{g.step === 'rules' ? 'Start preparation' : g.step === 'prepare' ? 'Start first ad' : g.step === 'perform' ? 'Collect guesses' : last ? 'Activity results' : 'Next team'}<ArrowRight size={18}/></button>}
    </footer>
    {g.step === 'reveal' && <nav className="pid-round-navigation" aria-label="Review commercials">{g.rounds.map((round, i) => <button key={round.id} className="button small-button secondary" aria-label={`Review commercial ${i + 1}`} aria-current={g.index === i ? 'step' : undefined} disabled={!round.revealed} onClick={() => update(s => reviewRound(s, i))}>{i + 1}{roundComplete(round) ? ' ✓' : ''}</button>)}</nav>}
  </main><Scoreboard segmentId={segment.segmentId} event={event} updateEvent={updateEvent} activeTeamId={g.step === 'rules' || g.step === 'prepare' ? undefined : team.id} playedCounts={Object.fromEntries(event.teams.map(t => [t.id, g.rounds.filter(round => round.teamId !== t.id && roundComplete(round)).length]))}/></div>;
}
