import { Lightbulb, Play, ArrowRight, Eye } from 'lucide-react';
import { EventTeams } from '../../src/core/teams/EventTeams';
import { Scoreboard } from '../../src/core/teams/Scoreboard';
import { Timer } from '../../src/core/play/TimerView';
import { useCountdown } from '../../src/core/play/timer';
import { segmentScore } from '../../src/core/scoring';
import { advance, reveal, scoreTeam, awardId, start } from './logic';
import type { Context } from './types';
import './style.css';
function Rules({ points }: { points: number }) {
  return <ol className="why-rules"><li>Think quietly for 10 seconds. Then everyone shares an idea with their team.</li><li>Agree on A, B or C. On the host’s count, all teams show 1, 2 or 3 fingers together, or say their choice.</li><li>Reveal the “why”. Each correct team gets {points} points; wrong guesses cost nothing.</li><li>Rotate who starts the discussion. Stay seated if you like. Wondering beats knowing!</li></ol>;
}
export function Setup(ctx: Context) {
  const { segment, event, update } = ctx;
  return <div className="setup-content"><div className="section-heading"><span className="eyebrow">PREDICT · DISCUSS · DISCOVER</span><h1>Wait, Why<span className="accent">?</span></h1><p>Every team plays every round. All the clues are on screen.</p></div><div className="aio-setup-grid"><section className="panel"><h2>Your event teams</h2><EventTeams teams={event.teams} players={event.players}/><p className="muted">For 10–40 people, aim for 3–5 per team. No phones, props or specialist knowledge needed.</p></section><section className="panel"><h2>The game plan</h2><Rules points={segment.points.correct}/><label className="aio-number"><span><b>Rounds</b><small>A fresh shuffled selection each game</small></span><select aria-label="Number of rounds" value={segment.settings.rounds} onChange={e => update(s => { s.settings.rounds = +e.target.value; })}>{[8, 10, 12].map(n => <option key={n} value={n}>{n}</option>)}</select></label><label className="aio-number"><span><b>Thinking & discussion</b><small>Seconds per round</small></span><select aria-label="Discussion seconds" value={segment.settings.seconds} onChange={e => update(s => { s.settings.seconds = +e.target.value; })}>{[45, 60, 90].map(n => <option key={n} value={n}>{n}</option>)}</select></label><p>About {Math.round(segment.settings.rounds * (segment.settings.seconds + 60) / 60)}–{Math.round(segment.settings.rounds * (segment.settings.seconds + 60) / 60) + 3} minutes, including reveals and discussion.</p></section></div><div className="setup-footer"><span className="privacy-note">15 puzzles included · saved on this laptop</span><button className="button primary large" disabled={!event.teams.length || event.teams.some(t => !t.name.trim())} onClick={() => start(ctx)}><Play size={20}/> Start activity</button></div></div>;
}
export function Stage(ctx: Context) {
  const { segment, event, update, updateEvent } = ctx, game = segment.game;
  const remaining = useCountdown(game.timer);
  const puzzle = game.deck[game.index], answered = game.step === 'answer';
  if (!puzzle) return <div className="empty-state"><h2>Set up your puzzles first.</h2><button className="button primary" onClick={() => update(s => { s.phase = 'setup'; })}>Game setup</button></div>;
  return <div className="stage-layout why-stage"><main className="game-stage">
    <div className="why-top"><span className="eyebrow">{game.step === 'rules' ? 'THE 30-SECOND BRIEF' : `ROUND ${game.index + 1} / ${game.deck.length} · ${puzzle.category}`}</span>{game.step !== 'rules' && (answered ? <div className="why-frozen-clock" role="timer" aria-label="Discussion timer stopped">{String(Math.floor(Math.ceil(remaining / 1000) / 60)).padStart(2, '0')}:{String(Math.ceil(remaining / 1000) % 60).padStart(2, '0')} <small>stopped</small></div> : <Timer state={game.timer} onChange={timer => update(s => { s.game.timer = timer; })} label="Discussion timer"/>)}</div>
    {game.step === 'rules' ? <section className="why-brief"><h1>Small puzzles.<br/>Big “aha!” moments.</h1><Rules points={segment.points.correct}/><p>Host: allow 30–60 seconds after each reveal to explore the explanation. Familiar puzzle? Let others reason first.</p></section> : <section className="why-puzzle"><h1>{answered ? `${"ABC"[puzzle.answer]} · ${puzzle.options[puzzle.answer]}` : puzzle.question}</h1>{!answered && <div className="why-options">{puzzle.options.map((text, i) => <div key={i} className={`why-option ${answered && puzzle.answer === i ? 'correct' : ''}`}><b>{'ABC'[i]}</b><span>{text}</span>{answered && puzzle.answer === i && <strong aria-label="Correct answer">✓</strong>}</div>)}</div>}{answered ? <div className="why-explanation"><h2><Lightbulb size={24}/> Here’s why</h2><p>{puzzle.explanation}</p><p className="why-wonder">Wonder together: {puzzle.wonder}</p></div> : <p className="why-cue" aria-live="polite">{remaining === 0 ? 'Time! All teams: show 1, 2 or 3 together.' : remaining > game.timer.durationMs - 10000 ? 'First 10 seconds: think quietly. Everyone gets a moment.' : 'Share an idea each, then agree on A, B or C.'}</p>}</section>}
    {answered && <div className="why-awards" aria-label="Award correct teams"><span>Correct teams · click again to undo</span><div>{event.teams.map((t, i) => { const awarded = event.scoreEntries.some(e => e.segmentId === segment.segmentId && e.roundId === awardId(segment, t.id) && e.active); return <button key={t.id} className="button secondary" aria-pressed={awarded} onClick={() => scoreTeam(ctx, i)}><kbd>{i + 1}</kbd>{t.name} {awarded ? '✓' : `+${segment.points.correct}`}</button>; })}</div></div>}
    <div className="why-actions">{game.step === 'question' ? <><span>Collect all teams’ choices before revealing.</span><button className="button primary large" onClick={() => update(s => reveal(s))}><Eye size={18}/> Reveal answer <kbd>R</kbd></button></> : <><span>{answered ? 'Award correct teams, then move on.' : 'Everyone plays. No speed bonus.'}</span><button className="button primary large" onClick={() => update(s => advance(s))}>{game.step === 'rules' ? 'Start first round' : game.index === game.deck.length - 1 ? 'Activity results' : 'Next round'}<ArrowRight size={18}/><kbd>N</kbd></button></>}</div>
  </main><Scoreboard segmentId={segment.segmentId} event={event} updateEvent={updateEvent} playedCounts={Object.fromEntries(event.teams.map(t => [t.id, game.index + (answered ? 1 : 0)]))}/></div>;
}
export function Finale({ segment, event }: Context) {
  const scores = event.teams.map(t => ({ ...t, score: segmentScore([...event.scoreEntries], segment.segmentId, t.id) })).sort((a, b) => b.score - a.score);
  return <main className="game-stage why-finale"><span className="eyebrow">WAIT, WHY? · ACTIVITY COMPLETE</span><h1>Take an “aha!” with you.</h1><p>Which explanation changed your mind? Share one with your team.</p><section className="panel"><h2>This activity’s scores</h2>{scores.map(t => <div className="aio-total" key={t.id}><span className="team-dot" style={{ background: t.color }}/><strong>{t.name}</strong><b>{t.score} pts</b></div>)}</section><details><summary>Revisit the discoveries</summary>{segment.game.deck.map(p => <article key={p.id}><h3>{p.question}</h3><p>{p.explanation}</p><p>{p.wonder}</p></article>)}</details></main>;
}
export function Preview() { return <div className="why-preview"><Lightbulb size={48}/><span className="eyebrow">TRUST YOUR INSTINCT?</span><strong>Think.<br/>Talk.<br/>Think again.</strong><span>A · B · C → Aha!</span></div>; }
