import { ArrowUpRight, ArrowRight, Play, ShieldCheck, Users, Monitor, Sparkles, Pencil, Check, PartyPopper } from 'lucide-react';
import { getActivities } from '../core/registry';
import type { Activity, AnySession, EventSession } from '../core/types';
export function Home({ session, event, onSetup, onDemo, onResume, onBuildEvent }: { session?: AnySession; event: EventSession; onSetup: (a: Activity) => void; onDemo: (a: Activity) => void; onResume: () => void; onBuildEvent: () => void }) {
  const activeEvent = !event.isDemo && (event.segments.length > 0 || event.scoreEntries.length > 0 || event.phase !== 'lineup');
  const current = event.segments[event.currentSegmentIndex];
  const resumeLabel = event.phase === 'lineup' ? 'Line-up builder' : event.phase === 'interstitial' ? 'Standings' : event.phase === 'wager' ? 'Final wager' : event.phase === 'finale' ? 'Event finale' : current ? `${current.title} · ${current.status === 'setup' ? 'setup' : current.status === 'play' ? 'in progress' : current.status}` : 'Saved event';
  return <main className="home-page"><section className="home-hero"><div><div className="eyebrow hero-eyebrow"><span/> LESS WORK. MORE PLAY.</div><h1>Good teams make<br/><span className="highlight-word">great memories<svg viewBox="0 0 600 20" aria-hidden="true"><path d="M6 12 Q220 -2 591 11 M42 18 Q290 7 555 17"/></svg></span><span className="accent">.</span></h1><p>Your little toolkit for a very good Friday.<br/>Bring the team. We’ll bring the fun.</p><div className="hero-details"><span><Monitor size={16}/> One laptop. One big screen.</span><span><Users size={16}/> The whole team.</span></div></div><div className="hero-note"><div className="note-pin"/><span className="handwritten">Today’s agenda:</span><strong>Make a memory.<br/>Share a laugh.</strong><span className="handwritten note-signature">No deadlines attached ☺</span><span className="note-star">✳</span></div><span className="hero-spark">✧</span></section>
    {activeEvent && <section className="resume-card active-event-card"><div><span className="eyebrow">ACTIVE EVENT · {resumeLabel}</span><h3>{event.title}</h3><p>{event.segments.length} activities · {event.people.filter(p => p.included).length} people · {event.teams.length} teams · Saved on this laptop</p></div><button className="button primary" onClick={onResume}>Continue event <ArrowRight size={18}/></button></section>}
    <section className="activity-section"><div className="section-label"><div><span className="eyebrow">THE ACTIVITY CUPBOARD</span><h2>{activeEvent ? 'Choose something new' : 'What are we playing?'}</h2></div><div className="button-row"><button className="button primary" onClick={onBuildEvent}>{activeEvent ? 'Start a new event' : 'Build an event'} <ArrowUpRight size={19}/></button><span className="pill"><span className="status-dot"/> {activeEvent ? 'Current event saved' : 'Ready when you are'}</span></div></div><div className="activities-grid">{getActivities().map(activity => { const card = activity.card ?? { label: 'THE NOSTALGIA EDITION', eyebrow: 'A TRIP DOWN MEMORY LANE', tags: [{ icon: Users, text: '1–8 teams' }, { icon: Check, text: 'No repeated photos' }, { text: '2 base points per correct guess' }] }; return <article className="activity-card" key={activity.id}><div className="activity-visual"><span className="activity-label"><Sparkles size={13}/> {card.label}</span>{activity.Preview && <activity.Preview session={session}/>}</div><div className="activity-copy"><div className="activity-card-top"><span className="eyebrow">{card.eyebrow}</span><span className="activity-icon"><activity.icon size={20}/></span></div><h2>{activity.name}</h2><p>{activity.description}</p><div className="activity-tags">{card.tags.map(tag => <span key={tag.text}>{tag.icon && <tag.icon size={14}/>}{tag.text}</span>)}</div><div className="activity-card-actions"><button className="button primary" onClick={() => onSetup(activity)}>{activeEvent ? 'Start a new game' : 'Set up your game'} <ArrowUpRight size={19}/></button><button className="button subtle" onClick={() => onDemo(activity)}><Play size={16}/> {activeEvent ? 'Try demo separately' : 'Try the demo'}</button></div></div></article>; })}<aside className="coming-soon-card"><span className="coming-soon-icon"><Pencil size={26}/><span>✦</span></span><span className="eyebrow">MORE GOOD TIMES AHEAD</span><h3>The next chapter<br/>is still being written.</h3><p>A growing collection of ways<br/>to bring your people together.</p><span className="handwritten">Leave a little room for fun.</span><div className="chalk-dots">○ ○ ○</div></aside></div></section>
    {event.isDemo && event.phase === 'lineup' && <section className="resume-card"><div><span className="eyebrow">READY TO BEGIN</span><h3>Build your Friday</h3><p>Choose one activity or make a full event line-up.</p></div><button className="button secondary" onClick={onBuildEvent}>Build an event <ArrowRight size={18}/></button></section>}
    <section className="how-it-works"><div><span className="eyebrow">THE FRIDAY FORMULA</span><h3>Less organising.<br/>More “remember when?”</h3></div><div><span className="step-badge yellow">1</span><h4>Make it yours</h4><p>A few photos. Your favourite people.</p></div><div><span className="step-badge pink">2</span><h4>Gather the gang</h4><p>Pick your teams and grab the big screen.</p></div><div><span className="step-badge blue">3</span><h4>Let the good times roll</h4><p>Guess, reveal, and make some noise.</p></div></section><div className="home-bottom"><span><ShieldCheck size={17}/> Private by design. Your photos stay with you.</span><span><PartyPopper size={17}/> Made for the people behind the job titles.</span></div>
  </main>;
}
