import { ArrowUpRight, ArrowRight, Play, ShieldCheck, Users, Monitor, Sparkles, Pencil, Check, PartyPopper } from 'lucide-react';
import { getActivities } from '../core/registry';
import type { Activity, AnySession } from '../core/types';
export function Home({ session, onSetup, onDemo, onResume, onBuildEvent }: { session?: AnySession; onSetup: (a: Activity) => void; onDemo: (a: Activity) => void; onResume: () => void; onBuildEvent: () => void }) {
  return <main className="home-page"><section className="home-hero"><div><div className="eyebrow hero-eyebrow"><span/> LESS WORK. MORE PLAY.</div><h1>Good teams make<br/><span className="highlight-word">great memories<svg viewBox="0 0 600 20" aria-hidden="true"><path d="M6 12 Q220 -2 591 11 M42 18 Q290 7 555 17"/></svg></span><span className="accent">.</span></h1><p>Your little toolkit for a very good Friday.<br/>Bring the team. We’ll bring the fun.</p><div className="hero-details"><span><Monitor size={16}/> One laptop. One big screen.</span><span><Users size={16}/> The whole team.</span></div></div><div className="hero-note"><div className="note-pin"/><span className="handwritten">Today’s agenda:</span><strong>Make a memory.<br/>Share a laugh.</strong><span className="handwritten note-signature">No deadlines attached ☺</span><span className="note-star">✳</span></div><span className="hero-spark">✧</span></section>
    <section className="activity-section"><div className="section-label"><div><span className="eyebrow">THE ACTIVITY CUPBOARD</span><h2>What are we playing?</h2></div><div className="button-row"><button className="button primary" onClick={onBuildEvent}>Build an event <ArrowUpRight size={19}/></button><span className="pill"><span className="status-dot"/> Ready when you are</span></div></div><div className="activities-grid">{getActivities().map(activity => <article className="activity-card" key={activity.id}><div className="activity-visual"><span className="activity-label"><Sparkles size={13}/> THE NOSTALGIA EDITION</span>{activity.Preview && session && <activity.Preview session={session}/>}</div><div className="activity-copy"><div className="activity-card-top"><span className="eyebrow">A TRIP DOWN MEMORY LANE</span><span className="activity-icon"><activity.icon size={20}/></span></div><h2>{activity.name}</h2><p>{activity.description}</p><div className="activity-tags"><span><Users size={14}/> 1–8 teams</span><span><Check size={14}/> No repeated photos</span><span>2 base points per correct guess</span></div><div className="activity-card-actions"><button className="button primary" onClick={() => onSetup(activity)}>Set up your game <ArrowUpRight size={19}/></button><button className="button subtle" onClick={() => onDemo(activity)}><Play size={16}/> Try the demo</button></div></div></article>)}<aside className="coming-soon-card"><span className="coming-soon-icon"><Pencil size={26}/><span>✦</span></span><span className="eyebrow">MORE GOOD TIMES AHEAD</span><h3>The next chapter<br/>is still being written.</h3><p>A growing collection of ways<br/>to bring your people together.</p><span className="handwritten">Leave a little room for fun.</span><div className="chalk-dots">○ ○ ○</div></aside></div></section>
    {session && !session.isDemo && <section className="resume-card"><div><span className="eyebrow">RIGHT WHERE YOU LEFT OFF</span><h3>{session.title}</h3><p>{session.people.filter(p => p.included).length} people · {session.teams.length} teams · Saved on this laptop</p></div><button className="button secondary" onClick={onResume}>Continue session <ArrowRight size={18}/></button></section>}
    <section className="how-it-works"><div><span className="eyebrow">THE FRIDAY FORMULA</span><h3>Less organising.<br/>More “remember when?”</h3></div><div><span className="step-badge yellow">1</span><h4>Make it yours</h4><p>A few photos. Your favourite people.</p></div><div><span className="step-badge pink">2</span><h4>Gather the gang</h4><p>Pick your teams and grab the big screen.</p></div><div><span className="step-badge blue">3</span><h4>Let the good times roll</h4><p>Guess, reveal, and make some noise.</p></div></section><div className="home-bottom"><span><ShieldCheck size={17}/> Private by design. Your photos stay with you.</span><span><PartyPopper size={17}/> Made for the people behind the job titles.</span></div>
  </main>;
}
