import { useState } from 'react';
import { Trophy, RotateCcw, Images, ArrowLeft, Sparkles } from 'lucide-react';
import { standings } from '../../../src/core/scoring';
import { StoredImage } from '../../../src/components/Images';
import { startNewGame } from '../logic/rounds';
import type { Context } from '../types';
export function Finale({ session, update }: Context) {
  const [view, setView] = useState<'results' | 'group'>('results');
  const ranking = standings(session.teams, session.scoreEntries), winners = ranking.filter(t => t.score === ranking[0].score);
  const podium = [ranking[1], ranking[0], ranking[2]].filter(Boolean);
  const spotlight = session.people.find(p => p.id === session.game.finale.spotlightPersonId), pair = session.facePairs.find(f => f.id === spotlight?.facePairId);
  const spot = session.game.finale.wipePosition >= 50 ? pair?.now?.faceBox : pair?.then?.faceBox;
  const image = session.assets[session.game.originalImageId!];
  return <main className="finale">{view === 'results' ? <><div className="finale-confetti" aria-hidden="true">✧ <span>✦</span> ✧ <span>✷</span> ✧</div><span className="eyebrow">MEETING ADJOURNED. MEMORIES MADE.</span><h1>{winners.length > 1 ? 'Sharing the trophy!' : 'Team of the month!'}</h1><p className="winner-name">{winners.map(t => t.name).join(' & ')}</p><p className="handwritten finale-caption">Turns out, some faces you never forget.</p><div className="podium">{podium.map(t => {
    const place = ranking.findIndex(r => r.id === t.id) + 1, tiedPlace = ranking.findIndex(r => r.score === t.score) + 1;
    return <div className={`podium-place place-${place}`} key={t.id} style={{ '--team-color': t.color } as React.CSSProperties}>{place === 1 && <Trophy className="podium-trophy" size={42}/>}<h3>{t.name}</h3><strong>{t.score}<span> {t.score === 1 ? 'point' : 'points'}</span></strong><div className="podium-block"><b>{tiedPlace === 1 ? '1st' : tiedPlace === 2 ? '2nd' : '3rd'}</b><span>{tiedPlace === 1 ? '★' : '✧'}</span></div></div>;
  })}</div>{ranking.length > 3 && <div className="rest-results">{ranking.slice(3).map((t, i) => <span key={t.id}>{i + 4}. {t.name} <b>{t.score}</b></span>)}</div>}<div className="button-row centered"><button className="button primary large" onClick={() => setView('group')}><Images size={20}/> The whole team reveal</button><button className="button secondary" onClick={() => update(startNewGame)}><RotateCcw size={18}/> Play again</button><button className="button subtle" onClick={() => update(s => { s.phase = 'setup'; s.setupStepId = 'game'; })}>Edit teams</button></div></> : <><div className="group-reveal-title"><button className="button subtle" onClick={() => setView('results')}><ArrowLeft size={18}/> Results</button><div><span className="eyebrow">ONE LAST THROWBACK</span><h1>Look how far we’ve come.</h1></div><Sparkles size={30}/></div><div className="group-wipe" style={{ aspectRatio: image ? image.width / image.height : 16 / 9, '--photo-ratio': image ? image.width / image.height : 16 / 9 } as React.CSSProperties}><StoredImage id={session.game.childhoodImageId} alt="The whole team as children"/><div className="wipe-now" style={{ clipPath: `inset(0 ${100 - session.game.finale.wipePosition}% 0 0)` }}><StoredImage id={session.game.originalImageId} alt="The whole team today"/></div><div className="wipe-line" style={{ left: `${session.game.finale.wipePosition}%` }}><span>↔</span></div><span className="wipe-label then">THEN</span><span className="wipe-label now">NOW</span>{spot && spotlight && <div className="spotlight-box" style={{ left: `${spot.x * 100}%`, top: `${spot.y * 100}%`, width: `${spot.width * 100}%`, height: `${spot.height * 100}%` }}><span>{spotlight.name}</span></div>}</div><label className="wipe-control"><span className="handwritten">Little legends</span><input aria-label="Reveal original group photo" type="range" min="0" max="100" value={session.game.finale.wipePosition} onChange={e => update(s => { s.game.finale.wipePosition = +e.target.value; })}/><span className="handwritten">All grown up</span></label><div className="spotlight-controls"><span className="eyebrow">IN THE SPOTLIGHT</span><button className={`button small-button ${!spotlight ? 'primary' : 'secondary'}`} onClick={() => update(s => { delete s.game.finale.spotlightPersonId; })}>Everyone</button>{session.people.filter(p => p.included).map(p => <button className={`button small-button ${spotlight?.id === p.id ? 'primary' : 'secondary'}`} key={p.id} onClick={() => update(s => { s.game.finale.spotlightPersonId = p.id; })}>{p.name}</button>)}</div></>}</main>;
}
