import { useState } from 'react';
import { Trophy, RotateCcw, Images, ArrowLeft } from 'lucide-react';
import { standings } from '../../../src/core/scoring';
import { StoredImage } from '../../../src/components/Images';
import { startNewGame } from '../logic/rounds';
import type { Context, CVEventUpdate } from '../types';
export function Finale({ segment, event, update, updateEvent }: Context) {
  const [view, setView] = useState<'results'|'group'>('results');
  const ranking = standings([...event.teams], [...event.scoreEntries]), winners = ranking.filter(t => t.score === ranking[0]?.score), spotlight = event.people.find(p => p.id === segment.game.finale.spotlightPersonId), pair = event.facePairs.find(f => f.id === spotlight?.facePairId), image = event.assets[segment.game.originalImageId!];
  const replay = () => { const e: CVEventUpdate = { ...event, people: [...event.people], facePairs: [...event.facePairs], teams: [...event.teams], scoreEntries: [...event.scoreEntries], assets: { ...event.assets } }; const s = structuredClone(segment); startNewGame(s, e); update(d => Object.assign(d, s)); updateEvent(d => Object.assign(d, e)); };
  return <main className="finale">{view === 'results' ? <><span className="eyebrow">MEETING ADJOURNED. MEMORIES MADE.</span><h1>{winners.length > 1 ? 'Sharing the trophy!' : 'Team of the month!'}</h1><p className="winner-name">{winners.map(t => t.name).join(' & ')}</p><div className="podium">{ranking.slice(0, 3).map((t, i) => <div className={`podium-place place-${i + 1}`} key={t.id} style={{ '--team-color': t.color } as React.CSSProperties}>{i === 0 && <Trophy size={42}/>}<h3>{t.name}</h3><strong>{t.score} points</strong></div>)}</div><div className="button-row centered"><button className="button primary large" onClick={() => setView('group')}><Images size={20}/> The whole team reveal</button><button className="button secondary" onClick={replay}><RotateCcw size={18}/> Play again</button><button className="button subtle" onClick={() => update(s => { s.phase = 'setup'; s.setupStepId = 'game'; })}>Edit teams</button></div></> : <><div className="group-reveal-title"><button className="button subtle" onClick={() => setView('results')}><ArrowLeft size={18}/> Results</button><h1>Look how far we’ve come.</h1></div><div className="group-wipe" style={{ aspectRatio: image ? image.width / image.height : 16 / 9 } as React.CSSProperties}><StoredImage id={segment.game.childhoodImageId} alt="The whole team as children"/><div className="wipe-now"><StoredImage id={segment.game.originalImageId} alt="The whole team today"/></div></div><label className="wipe-control"><span>Little legends</span><input aria-label="Reveal original group photo" type="range" min="0" max="100" value={segment.game.finale.wipePosition} onChange={e => update(s => { s.game.finale.wipePosition = +e.target.value; })}/><span>All grown up</span></label><div className="spotlight-controls"><span className="eyebrow">IN THE SPOTLIGHT</span>{event.people.filter(p => p.included).map(p => <button className="button small-button" key={p.id} onClick={() => update(s => { s.game.finale.spotlightPersonId = p.id; })}>{p.name}</button>)}</div></>}</main>;
}
