import { ArrowLeft, ArrowRight, Check, Eye, X, Trophy } from 'lucide-react';
import { StoredImage } from '../../../src/components/Images';
import { Scoreboard } from '../../../src/core/teams/Scoreboard';
import { StealPanel } from '../../../src/core/play/StealPanel';
import { markResult, markSteal, moveRound, reveal } from '../logic/rounds';
import type { Context } from '../types';
export function Stage(context: Context) {
  const { session, update } = context, game = session.game, round = game.rounds[game.currentRoundIndex];
  if (!round) return <div className="empty-state"><h2>The team is nearly ready.</h2><button className="button primary" onClick={() => update(s => { s.phase = 'setup'; s.setupStepId = 'game'; })}>Set up game</button></div>;
  const person = session.people.find(p => p.id === round.personId), pair = session.facePairs.find(p => p.id === person?.facePairId), team = session.teams.find(t => t.id === round.teamId)!;
  if (!person || !pair) return <div className="empty-state">This round’s person is missing. Return to setup to start a new game.</div>;
  const teamRounds = game.rounds.filter(r => r.teamId === team.id), teamPhoto = teamRounds.findIndex(r => r.id === round.id) + 1;
  const next = game.rounds[game.currentRoundIndex + 1], nextTeam = next && session.teams.find(t => t.id === next.teamId);
  const complete = game.rounds.every(r => r.result !== null);
  return <div className="stage-layout"><main className={`game-stage ${round.revealed ? 'revealed' : ''}`}>
    <div className="round-header"><div className="active-team" style={{ '--team-color': team.color } as React.CSSProperties}><span className="team-dot" style={{ background: team.color }}/><div><small>IN THE HOT SEAT</small><strong>{team.name}</strong></div></div><div className="round-count"><span>Photo <b>{game.currentRoundIndex + 1}</b> of {game.rounds.length}</span><small>{teamPhoto} / {teamRounds.length} in this team’s set</small></div><div className="point-stake"><b>{session.points.correct}</b><span>POINT<br/>UP FOR GRABS</span></div></div>
    <div className="round-scene" key={round.id}><span className="scene-doodle doodle-left">✧</span><span className="scene-doodle doodle-right">✷</span>
      {!round.revealed ? <><div className="question-intro"><span className="eyebrow">THE ULTIMATE THROWBACK</span><h1>Recognise this little legend?</h1></div><div className="polaroid childhood-polaroid"><span className="tape"/><StoredImage id={pair.then?.cropImageId} alt="The childhood face to guess" draggable={false}/><span className="handwritten polaroid-caption">Who is this?</span></div><p className="stage-prompt handwritten">Same person. Slightly smaller shoes.</p></> : <><div className="reveal-polaroids"><div className="polaroid then-reveal"><StoredImage id={pair.then?.cropImageId} alt={`${person.name} as a child`}/><span className="handwritten polaroid-caption">back then</span></div><span className="reveal-arrow handwritten">→</span><div className="polaroid now-reveal"><span className="tape pink"/><StoredImage id={pair.now?.cropImageId} alt={`${person.name} now`}/><span className="handwritten polaroid-caption">all grown up</span></div></div><div className="reveal-name"><span className="eyebrow">LOOK WHO IT IS!</span><h1>{person.name}</h1>{person.funFact && <p>{person.funFact}</p>}</div></>}
    </div>
    <div className="round-actions">{!round.revealed ? <button className="button primary large" onClick={() => update(reveal)}><Eye size={20}/> Reveal the grown-up <kbd>↵</kbd></button> : <><div className="result-buttons"><button className={`button ${round.result === 'correct' ? 'correct selected' : 'secondary'}`} aria-pressed={round.result === 'correct'} onClick={() => update(s => markResult(s, 'correct'))}><Check size={21}/> Correct <b>+{session.points.correct}</b><kbd>C</kbd></button><button className={`button ${round.result === 'missed' ? 'missed selected' : 'secondary'}`} aria-pressed={round.result === 'missed'} onClick={() => update(s => markResult(s, 'missed'))}><X size={19}/> Missed <b>0</b><kbd>M</kbd></button></div>{round.result === 'missed' && <StealPanel teams={session.teams} ownerTeamId={team.id} segmentId={session.segmentId} roundId={round.id} entries={session.scoreEntries} points={session.points.steal} onSteal={id => update(s => markSteal(s, id))}/>}<button className="button primary" disabled={round.result === null || (!next && !complete)} onClick={() => update(s => moveRound(s, 1))}>{next ? nextTeam?.id !== team.id ? `Next team: ${nextTeam?.name}` : 'Next photo' : 'Final results'}{next ? <ArrowRight size={18}/> : <Trophy size={18}/>}</button></>}</div>
    <div className="round-navigation"><button className="icon-button" aria-label="Previous photo" disabled={game.currentRoundIndex === 0} onClick={() => update(s => moveRound(s, -1))}><ArrowLeft size={18}/></button><div className="round-squares" aria-label="Jump to a round">{game.rounds.map((r, i) => <button key={r.id} aria-label={`Photo ${i + 1}, ${r.result ?? (r.revealed ? 'revealed' : 'unplayed')}`} aria-current={i === game.currentRoundIndex ? 'step' : undefined} className={`round-square ${r.result ?? ''} ${r.revealed ? 'played' : ''}`} style={{ '--team-color': session.teams.find(t => t.id === r.teamId)?.color } as React.CSSProperties} onClick={() => update(s => { s.game.currentRoundIndex = i; })}>{r.result === 'correct' ? '✓' : r.result === 'missed' ? '−' : ''}</button>)}</div><button className="icon-button" aria-label="Next photo" disabled={!next} onClick={() => update(s => moveRound(s, 1))}><ArrowRight size={18}/></button></div>
    {!next && !complete && round.revealed && <p className="warning-text small centered">Record a result for every photo to finish. Use the squares to revisit unscored rounds.</p>}
  </main><Scoreboard session={session} update={update} activeTeamId={team.id} playedCounts={Object.fromEntries(session.teams.map(t => [t.id, game.rounds.filter(r => r.teamId === t.id && r.result !== null).length]))}/></div>;
}
