import { ArrowLeft, ArrowRight, Check, Eye, X, Trophy } from 'lucide-react';
import { StoredImage } from '../../../src/components/Images';
import { RevealAnswer } from '../../../src/components/RevealAnswer';
import { Scoreboard } from '../../../src/core/teams/Scoreboard';
import { StealPanel } from '../../../src/core/play/StealPanel';
import { eventDraft } from '../../../src/core/event';
import { furthestRound, goToRound, markResult, markSteal, moveRound, reveal } from '../logic/rounds';
import type { Context, CVEventUpdate, CVSession } from '../types';

export function Stage(context: Context) {
  const { segment, event, update, updateEvent } = context, game = segment.game, round = game.rounds[game.currentRoundIndex];
  if (!round) return <div className="empty-state"><h2>The team is nearly ready.</h2><button className="button primary" onClick={() => update(s => { s.phase = 'setup'; s.setupStepId = 'game'; })}>Set up game</button></div>;
  const person = event.people.find(p => p.id === round.personId), pair = event.facePairs.find(p => p.id === person?.facePairId), team = event.teams.find(t => t.id === round.teamId)!;
  if (!person || !pair || !team) return <div className="empty-state">This round’s person is missing.</div>;
  const teamRounds = game.rounds.filter(r => r.teamId === team.id), teamPhoto = teamRounds.findIndex(r => r.id === round.id) + 1, next = game.rounds[game.currentRoundIndex + 1], nextTeam = next && event.teams.find(t => t.id === next.teamId), complete = game.rounds.every(r => r.result !== null), furthest = furthestRound(game.rounds);
  const scoreChange = (fn: (s: CVSession, e: CVEventUpdate) => void) => { const e: CVEventUpdate = eventDraft(event); update(s => fn(s, e)); updateEvent(d => { d.scoreEntries = e.scoreEntries; }); };
  return <div className="stage-layout cvn-stage"><main className={`game-stage ${round.revealed ? 'revealed' : ''}`}>
    <div className="round-header"><div className="active-team" style={{ '--team-color': team.color } as React.CSSProperties}><span className="team-dot" style={{ background: team.color }}/><div><small>IN THE HOT SEAT</small><strong>{team.name}</strong></div></div><div className="round-count"><span>Photo <b>{game.currentRoundIndex + 1}</b> of {game.rounds.length}</span><small>{teamPhoto} / {teamRounds.length} in this team’s set</small></div><div className="point-stake"><b>{segment.points.correct}</b><span>POINT<br/>UP FOR GRABS</span></div></div>
    <div className="round-scene" key={round.id}>{!round.revealed ? <><div className="question-intro"><span className="eyebrow">THE ULTIMATE THROWBACK</span><h1>Recognise this little legend?</h1></div><div className="polaroid childhood-polaroid"><StoredImage id={pair.then?.cropImageId} alt="The childhood face to guess"/><span className="handwritten polaroid-caption">Who is this?</span></div></> : <><div className="reveal-polaroids"><div className="polaroid then-reveal"><StoredImage id={pair.then?.cropImageId} alt={`${person.name} as a child`}/><span className="handwritten polaroid-caption">back then</span></div><span className="reveal-arrow handwritten">→</span><div className="polaroid now-reveal"><StoredImage id={pair.now?.cropImageId} alt={`${person.name} now`}/><span className="handwritten polaroid-caption">all grown up</span></div></div><RevealAnswer eyebrow="LOOK WHO IT IS!" title={person.name} description={person.funFact}>{round.result === 'correct' && <div className="correct-stamp" aria-hidden="true"><b>+{segment.points.correct}</b><span>CORRECT<small>{team.name}</small></span></div>}</RevealAnswer></>}</div>
    <div className="round-actions">{!round.revealed ? <button className="button primary large" onClick={() => update(reveal)}><Eye size={20}/> Reveal the grown-up</button> : <><div className="result-buttons"><button className="button secondary" onClick={() => scoreChange((s,e) => markResult(s,e,'correct'))}><Check size={21}/> Correct <b>+{segment.points.correct}</b></button><button className="button secondary" onClick={() => scoreChange((s,e) => markResult(s,e,'missed'))}><X size={19}/> Missed <b>0</b></button></div>{round.result === 'missed' && <StealPanel teams={[...event.teams]} ownerTeamId={team.id} segmentId={segment.segmentId} roundId={round.id} entries={[...event.scoreEntries]} points={segment.points.steal} onSteal={id => scoreChange((s,e) => markSteal(s,e,id))}/>}<button className="button primary" disabled={round.result === null || (!next && !complete)} onClick={() => update(s => moveRound(s, 1))}>{next ? `Next ${nextTeam?.name ?? 'photo'}` : 'Activity results'}{next ? <ArrowRight size={18}/> : <Trophy size={18}/>}</button></>}</div>
    <div className="round-navigation"><button className="icon-button" aria-label="Previous photo" disabled={game.currentRoundIndex === 0} onClick={() => update(s => moveRound(s, -1))}><ArrowLeft size={18}/></button><div className="round-squares">{game.rounds.map((r, i) => <button key={r.id} aria-label={`Photo ${i + 1}`} disabled={i > furthest} onClick={() => update(s => goToRound(s, i))}>{r.result === 'correct' ? '✓' : r.result === 'missed' ? '−' : ''}</button>)}</div><button className="icon-button" aria-label="Next photo" disabled={game.currentRoundIndex >= furthest} onClick={() => update(s => moveRound(s, 1))}><ArrowRight size={18}/></button></div>
  </main><Scoreboard segmentId={segment.segmentId} event={event} updateEvent={updateEvent} activeTeamId={team.id} playedCounts={Object.fromEntries(event.teams.map(t => [t.id, game.rounds.filter(r => r.teamId === t.id && r.result !== null).length]))}/></div>;
}
