import { Play, Shuffle, Users, Check, Flag } from 'lucide-react';
import { TeamEditor } from '../../../src/core/teams/TeamEditor';
import { prepareCrops } from '../logic/preparation';
import { startNewGame } from '../logic/rounds';
import type { Context } from '../types';
export function GameSetupStep({ session, update, runTask }: Context) {
  const count = session.people.filter(p => p.included).length;
  const missing = session.people.filter(p => p.included && !p.name.trim()).length;
  const valid = count > 0 && missing === 0 && session.teams.every(t => t.name.trim());
  return <div className="setup-content"><div className="section-heading"><span className="eyebrow">04 / PICK YOUR CLASSMATES</span><h1>A little team spirit<span className="accent">.</span></h1><p>Different photos for every team. Two points for every familiar face — one if another team steals it.</p></div>
    <div className="game-setup-grid"><section className="panel"><div className="panel-heading"><Users size={21}/><h2>Meet the teams</h2></div><p className="muted">Choose your names and wear your colours.</p><TeamEditor teams={session.teams} onChange={teams => update(s => { s.teams = teams; })}/></section><section className="panel assignment-panel"><div className="panel-heading"><Flag size={21}/><h2>The game plan</h2></div><div className="rule-card"><strong>01</strong><div><b>One team at a time</b><p>Each team gets its own set of childhood photos.</p></div></div><div className="rule-card"><strong>02</strong><div><b>Guess. Reveal. Celebrate.</b><p>Correct = 2 points. Stolen = 1. Missed = 0.</p></div></div><div className="rule-card"><strong>03</strong><div><b>No repeats, anywhere</b><p>Every person appears just once in the game.</p></div></div><label className="shuffle-control"><Shuffle size={18}/><span><b>Shuffle the photos</b><small>A fresh surprise every game</small></span><input type="checkbox" className="switch" checked={session.settings.shuffle} onChange={e => update(s => { s.settings.shuffle = e.target.checked; })}/></label></section></div>
    <section className="allocation"><div><span className="eyebrow">YOUR PHOTO LINE-UP</span><h3>{count} people. {session.teams.length} teams. All new faces.</h3></div><div className="allocation-teams">{session.teams.map((t, i) => <div key={t.id}><span className="team-dot" style={{ background: t.color }}/><span>{t.name || 'Unnamed team'}</span><b>{Math.floor(count / session.teams.length) + (i < count % session.teams.length ? 1 : 0)} photos</b></div>)}</div>{count % session.teams.length !== 0 && <p className="warning-text small">The set does not divide evenly. Earlier teams get one extra photo. Change the team count or included people for equal sets.</p>}{count < session.teams.length && <p className="warning-text">Some teams have no photos. Reduce the number of teams or include more people.</p>}{missing > 0 && <p className="warning-text">Name {missing} more people before starting.</p>}</section>
    <div className="setup-footer"><span className="privacy-note"><Check size={17}/> Everything is saved on this laptop</span><button className="button primary large" disabled={!valid || count < session.teams.length} onClick={() => void runTask('Getting the team ready…', async () => { const next = await prepareCrops(session); startNewGame(next); update(s => Object.assign(s, next)); })}><Play size={20}/> Start new game</button></div>
  </div>;
}
