import { useRef, useState } from 'react';
import { ArrowRight, Download, FileUp, Trash2, X } from 'lucide-react';
import { CropPreview } from '../../../src/components/Images';
import { PhotoEditor } from '../../../src/components/PhotoEditor';
import { parseNames } from '../../../src/core/people/csv';
import { exportFacePairs } from '../../../src/core/transfer';
import { prepareCrops } from '../logic/preparation';
import type { Context } from '../types';
export function NamePeopleStep({ session, update, runTask, notify }: Context) {
  const [selected, setSelected] = useState(session.people[0]?.facePairId), [csv, setCsv] = useState<ReturnType<typeof parseNames>>();
  const input = useRef<HTMLInputElement>(null);
  const sorted = [...session.people].sort((a, b) => { const x = session.facePairs.find(p => p.id === a.facePairId)?.now?.faceBox, y = session.facePairs.find(p => p.id === b.facePairId)?.now?.faceBox; return (x ? x.x + x.width / 2 : 2) - (y ? y.x + y.width / 2 : 2) || (x?.y ?? 0) - (y?.y ?? 0); });
  const nowId = session.game.originalImageId!, thenId = session.game.childhoodImageId!, now = session.assets[nowId];
  const missing = session.people.filter(p => p.included && !p.name.trim()).length;
  return <div className="setup-content wide"><div className="section-heading"><span className="eyebrow">03 / TAKE ATTENDANCE</span><h1>Put a name to that face<span className="accent">.</span></h1><p>A familiar face deserves a proper introduction. Fun facts appear only after the reveal.</p></div>
    <div className="names-toolbar"><span>{session.people.filter(p => p.included).length} classmates in the game {missing > 0 && <span className="warning-text">· {missing} need a name</span>}</span><div className="button-row"><input type="file" accept=".csv,text/csv" ref={input} className="visually-hidden" aria-label="Import names CSV" onChange={e => { const file = e.target.files?.[0]; if (file) void file.text().then(text => { try { const parsed = parseNames(text); if (!parsed.length) throw new Error('The CSV has no names.'); setCsv(parsed); } catch (error) { notify((error as Error).message); } }); e.target.value = ''; }}/><button className="button secondary" onClick={() => input.current?.click()}><FileUp size={16}/> Import names</button><button className="button secondary" onClick={() => void runTask('Packing your face pairs…', async () => { const next = await prepareCrops(session); update(s => Object.assign(s, next)); await exportFacePairs(next); })}><Download size={16}/> Export face pairs</button></div></div>
    {now && <details className="group-reference" open><summary>Find a person in the group photos</summary><div className="photo-pair-grid">{(['now', 'then'] as const).map(side => <div key={side}><span className="eyebrow">{side}</span><PhotoEditor imageId={session.game.previews[side === 'now' ? nowId : thenId] || (side === 'now' ? nowId : thenId)} aspect={now.width / now.height} pairs={session.facePairs} side={side} selected={selected} mode="pair" onSelect={setSelected} onChange={() => {}} onAdd={() => {}}/></div>)}</div></details>}
    <div className="people-table"><div className="people-table-heading"><span>THEN / NOW</span><span>NAME & AFTER-REVEAL FUN FACT</span><span>CROP PADDING</span><span>IN GAME</span></div>{sorted.map(person => {
      const pair = session.facePairs.find(p => p.id === person.facePairId)!;
      const padding = pair.then?.padding.top ?? .4;
      return <div className={`person-row ${selected === pair.id ? 'selected' : ''}`} key={person.id}><div className="person-crops" onClick={() => setSelected(pair.id)}><span className="person-number">{pair.number}</span><CropPreview face={pair.then} assets={session.assets} previews={session.game.previews} label={`Childhood face ${pair.number}`}/><CropPreview face={pair.now} assets={session.assets} previews={session.game.previews} label={`Current face ${pair.number}`}/></div><div className="person-fields"><input aria-label={`Name for person ${pair.number}`} placeholder="Who’s this?" maxLength={80} value={person.name} onFocus={() => setSelected(pair.id)} onChange={e => update(s => { s.people.find(p => p.id === person.id)!.name = e.target.value; })}/><input aria-label={`Fun fact for person ${pair.number}`} placeholder="A little fun fact (optional)" maxLength={240} value={person.funFact} onFocus={() => setSelected(pair.id)} onChange={e => update(s => { s.people.find(p => p.id === person.id)!.funFact = e.target.value; })}/>{(!pair.now || !pair.then) && <small className="warning-text">Missing a face — finish matching before including.</small>}</div><label className="padding-slider"><span>Hair & shoulders</span><input aria-label={`Crop padding for person ${pair.number}`} type="range" min="0" max="1" step=".05" value={padding} onChange={e => update(s => { const p = s.facePairs.find(p => p.id === pair.id)!; const v = +e.target.value; for (const f of [p.now, p.then]) if (f) { f.padding = { top: v, left: v * .8, right: v * .8, bottom: v * 1.75 }; f.cropImageId = undefined; } })}/></label><div className="person-actions"><input type="checkbox" className="switch" aria-label={`Include person ${pair.number}`} checked={person.included} disabled={!pair.now || !pair.then} onChange={e => update(s => { s.people.find(p => p.id === person.id)!.included = e.target.checked; })}/><button className="icon-button danger" aria-label={`Delete person ${pair.number}`} onClick={() => update(s => { s.people = s.people.filter(p => p.id !== person.id); s.facePairs = s.facePairs.filter(p => p.id !== pair.id); })}><Trash2 size={17}/></button></div></div>;
    })}</div>
    <div className="setup-footer"><button className="button subtle" onClick={() => update(s => { s.setupStepId = 'match'; })}>Back to matching</button><button className="button primary" disabled={missing > 0 || !session.people.some(p => p.included)} onClick={() => void runTask('Saving the final crops…', async () => { const next = await prepareCrops(session); next.setupStepId = 'game'; update(s => Object.assign(s, next)); })}>Set up the game <ArrowRight size={18}/></button></div>
    {csv && <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="csv-title"><button className="modal-close icon-button" aria-label="Close CSV preview" onClick={() => setCsv(undefined)}><X/></button><span className="eyebrow">CHECK THE REGISTER</span><h2 id="csv-title">Import names</h2><p>Names map to current faces from left to right. For multiple rows, check the numbered preview carefully.</p><div className="csv-preview">{csv.map((row, i) => <div key={i}><span>Face {session.facePairs.find(p => p.id === sorted[i]?.facePairId)?.number ?? '—'}</span><strong>{row.name || '(empty name)'}</strong></div>)}</div>{csv.length !== sorted.length && <p className="warning-text">{csv.length} names for {sorted.length} people. Update the CSV so the counts match.</p>}<button className="button primary" disabled={csv.length !== sorted.length || csv.some(n => !n.name)} onClick={() => { update(s => csv.forEach((row, i) => { const person = s.people.find(p => p.id === sorted[i].id)!; person.name = row.name; person.funFact = row.funFact; })); setCsv(undefined); notify('Class register updated.'); }}>Apply names</button></section></div>}
  </div>;
}
